### ISSUE TITLE
Address pagespeed results.

### ISSUE THREAD

**Issue by lucavallin** [lucavallin/verto#284]
See results from pagespeed: https://pagespeed.web.dev/analysis/https-verto-sh/25810z45zq?form_factor=mobile.

We should address them as much as possible.

**Comment by Bitnagar** [comment]
I was able to get the `Accessibility` score to `100` on my localhost production build.

![image](https://github.com/lucavallin/verto/assets/88842947/b4b42ced-f249-4fd2-9d24-5315910b4872)


Changes made for above `accessibility` score:
- Changed the `aria-label` attribute value to match the text content of the element.
- Changed the `text-gray` color of `headings` or `subheadings` to `text-gray-900` (nearly white), so that the contrast ratio between the  `background-color` and the `foreground text` remains as per standards.
- Changed the `search bar` background color to `bg-transparent`  so that contrast ratio remains as per standards.

These changes corresponds to the errors/suggestions given in `PageSpeed Insights` link attached in issue.

The performance score went down to 70, could be because of platform. I think making a PR would not change the current live performance score. I can make one if you consider. @lucavallin

**Comment by lucavallin** [comment]
@Bitnagar Feel free to make a PR with those changes, I don't think they impact performance in prod.

**Comment by ruchikamuddinagiri** [comment]
Is this issue still open? There could be scope to further improve accessibility. Can I take a stab at it?

**Comment by lucavallin** [comment]
@ruchikamuddinagiri feel free to run the tool and make any improvements you'd like!
